laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
	Route::resource('etapas', 'Painel\EtapasController');
	Route::resource('textos', 'Painel\TextosController');
});

laravel/app/models/Etapa.php
<?php

class Etapa extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'posts_etapas';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function posts()
    {
    	return $this->hasMany('Texto', 'posts_etapas_id');
    }
}

laravel/app/controllers/painel/EtapasController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Etapa;

class EtapasController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.etapas.index')->with('etapas', Etapa::orderBy('ordem', 'asc')->get());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.etapas.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Etapa;

		$object->titulo = Input::get('titulo');

		try {

			$object->save();

			$object->slug = Str::slug($object->id.'-'.Input::get('titulo'));
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Etapa criada com sucesso.');
			return Redirect::route('painel.etapas.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(['Erro ao criar Etapa!']);	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.etapas.edit')->with('etapa', Etapa::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Etapa::find($id);

		$object->titulo = Input::get('titulo');
		
		try {

			$object->save();

			$object->slug = Str::slug($object->id.'-'.Input::get('titulo'));
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Etapa alterada com sucesso.');
			return Redirect::route('painel.etapas.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(['Erro ao criar Etapa!']);	

		}		
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Etapa::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Etapa removida com sucesso.');

		return Redirect::route('painel.etapas.index');
	}

}

laravel/app/views/backend/etapas/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Etapa
        </h2>  

		{{ Form::open( array('route' => array('painel.etapas.update', $etapa->id), 'files' => false, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputCampo">Título</label>
					<input type="text" class="form-control" id="inputCampo" name="titulo"  value="{{ $etapa->titulo }}" required>
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.etapas.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/etapas/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Etapa
        </h2>  

		<form action="{{URL::route('painel.etapas.store')}}" method="post">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputCampo">Título</label>
					<input type="text" class="form-control" id="inputCampo" name="titulo"  @if(Session::has('formulario')) value="{{ Session::get('formulario')['titulo'] }}" @endif required>
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.etapas.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/etapas/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

	@if($errors->any())
		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
	@endif

	<h2>
  		Etapas <a href="{{ URL::route('painel.etapas.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span>  Adicionar Etapa</a>
	</h2>

	<table class="table table-striped table-bordered table-hover table-sortable" data-tabela="posts_etapas">
        
        <thead>
    		<tr>
            <th>Ordenar</th>
            <th>Título</th>
      			<th><span class="glyphicon glyphicon-cog"></span></th>
    		</tr>
  		</thead>

  		<tbody>
    	@foreach ($etapas as $registro)

        	<tr class="tr-row" id="row_{{ $registro->id }}">
           	<td class="move-actions"><a href="#" class="btn btn-info btn-move btn-sm">mover</a></td>
           	<td>{{$registro->titulo}}</td>
            <td class="crud-actions">
          	  <a href="{{ URL::route('painel.etapas.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

              {{ Form::open(array('route' => array('painel.etapas.destroy', $registro->id), 'method' => 'delete')) }}
                <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
              {{ Form::close() }}
            </td>
        	</tr>

    	@endforeach
  		</tbody>

    </table>
    
</div>

@stop