laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
	Route::resource('etapas', 'Painel\EtapasController');
	Route::resource('textos', 'Painel\TextosController');
});

laravel/app/models/Usuario.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class Usuario extends Eloquent implements UserInterface, RemindableInterface {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('senha');

	// array of attributes we CAN set on the backend
    protected $fillable = array('username', 'email', 'senha');

    // and those we CAN'T  set on the backend
    protected $guarded = array('id');

	/**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
	public function getAuthIdentifier()
	{
		return $this->getKey();
	}

	/**
	 * Get the password for the user.
	 *
	 * @return string
	 */
	public function getAuthPassword()
	{
		return $this->password;
	}

	/**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
	public function getReminderEmail()
	{
		return $this->email;
	}

}

laravel/app/controllers/painel/UsuariosController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Hash, Usuario;

class UsuariosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.usuarios.index')->with('usuarios', Usuario::all());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.usuarios.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Usuario;

		$object->email = Input::get('email');
		$object->username = Input::get('username');
		$object->password = Hash::make(Input::get('password'));
		
		if(!Input::get('username') || !Input::get('password') || (Input::get('password') != Input::get('password_confirm'))){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(['Erro ao criar usuário! Verifique se os campos estão devidamente preenchidos e que a confirmação de senha é igual à senha informada']);
		}else{
			try {

				$object->save();
				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Usuário criado com sucesso.');
				return Redirect::route('painel.usuarios.index');

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(['Erro ao criar usuário! Verifique se o nome de usuário ou o email não estão sendo utilizados.']);	

			}
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.usuarios.edit')->with('usuario', Usuario::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Usuario::find($id);

		$object->email = Input::get('email');
		$object->username = Input::get('username');
		
		if(Input::has('password')){
			if(Input::get('password') == Input::get('password_confirm')){
				$object->password = Hash::make(Input::get('password'));
			}else{
				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(['Erro ao criar usuário! Verifique se os campos estão devidamente preenchidos e que a confirmação de senha é igual à senha informada']);
			}
		}
		
		if(!Input::get('username')){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(['Erro ao criar usuário! Verifique se os campos estão devidamente preenchidos e que a confirmação de senha é igual à senha informada']);
		}else{
			try {

				$object->save();
				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Usuário alterado com sucesso.');
				return Redirect::route('painel.usuarios.index');

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(['Erro ao criar usuário! Verifique se o nome de usuário ou o email não estão sendo utilizados.']);	

			}
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Usuario::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Usuário removido com sucesso.');

		return Redirect::route('painel.usuarios.index');
	}

}

laravel/app/views/backend/usuarios/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Usuário
        </h2>  

		{{ Form::open( array('route' => array('painel.usuarios.update', $usuario->id), 'files' => false, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputUsuario">Usuário</label>
					<input type="text" class="form-control" id="inputUsuario" name="username"  value="{{ $usuario->username }}" required>
				</div>

				<div class="form-group">
					<label for="inputEmail">E-mail</label>
					<input type="email" class="form-control" id="inputEmail" name="email" value="{{ $usuario->email }}">
				</div>

				<div class="form-group">
					<label for="inputSenha">Senha</label>
					<input type="password" class="form-control" id="inputSenha" name="password">
				</div>

				<div class="form-group">
					<label for="inputConfSenha">Digite novamente a Senha</label>
					<input type="password" class="form-control" id="inputConfSenha" name="password_confirm">
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.usuarios.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/usuarios/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Usuário
        </h2>  

		<form action="{{URL::route('painel.usuarios.store')}}" method="post">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

		    	<div class="form-group">
					<label for="inputUsuario">Usuário</label>
					<input type="text" class="form-control" id="inputUsuario" name="username"  @if(Session::has('formulario')) value="{{ Session::get('formulario')['username'] }}" @endifrequired>
				</div>

				<div class="form-group">
					<label for="inputEmail">E-mail</label>
					<input type="email" class="form-control" id="inputEmail" name="email" @if(Session::has('formulario')) value="{{ Session::get('formulario')['email'] }}" @endif>
				</div>

				<div class="form-group">
					<label for="inputSenha">Senha</label>
					<input type="password" class="form-control" id="inputSenha" name="password"  @if(Session::has('formulario')) value="{{ Session::get('formulario')['password'] }}" @endifrequired>
				</div>

				<div class="form-group">
					<label for="inputConfSenha">Digite novamente a Senha</label>
					<input type="password" class="form-control" id="inputConfSenha" name="password_confirm" @if(Session::has('formulario')) value="{{ Session::get('formulario')['password_confirm'] }}" @endif required>
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.usuarios.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/usuarios/index.blade.php
@section('conteudo')

    <div class="container">

    	@if(Session::has('sucesso'))
    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
        @endif

    	@if($errors->any())
    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    	@endif

      	<h2>
        	Usuários <a href="{{ URL::route('painel.usuarios.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Usuário</a>
        </h2>

      	<table class="table table-striped table-bordered table-hover">

      		<thead>
        		<tr>
          			<th>Usuário</th>
          			<th>E-mail</th>
          			<th><span class="glyphicon glyphicon-cog"></span></th>
        		</tr>
      		</thead>

      		<tbody>
        	@foreach ($usuarios as $usuario)

            	<tr class="tr-row">
              		<td>
                        {{ $usuario->username }}
                    </td>
              		<td>
                        {{ $usuario->email }}
                    </td>
              		<td class="crud-actions">
                		<a href="{{ URL::route('painel.usuarios.edit', $usuario->id ) }}" class="btn btn-primary btn-sm">editar</a>
                        
                        @if(Auth::user()->id != $usuario->id)
                    	   {{ Form::open(array('route' => array('painel.usuarios.destroy', $usuario->id), 'method' => 'delete')) }}
                                <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                           {{ Form::close() }}
                       @endif
              		</td>
            	</tr>

        	@endforeach
      		</tbody>

    	</table>
    </div>

@stop