laravel/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
	Route::resource('etapas', 'Painel\EtapasController');
	Route::resource('textos', 'Painel\TextosController');
});

laravel/app/models/Texto.php
<?php

class Texto extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'posts';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function etapa()
    {
    	return $this->belongsTo('Etapa', 'posts_etapas_id');
    }
}

laravel/app/controllers/painel/TextosController.php
<?php

namespace Painel;

use View, Input, Str, Session, Redirect, Texto, Etapa;

class TextosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		if(Input::get('etapa')){
			$filtroEtapa = Input::get('etapa');
			$posts = Etapa::find($filtroEtapa)->posts()->orderBy('ordem', 'asc')->get();
		}else{
			$filtroEtapa = false;
			$posts = false;
		}

		$this->layout->content = View::make('backend.textos.index')->with('textos', $posts)
																	->with('etapas', Etapa::orderBy('ordem', 'asc')->get())
																	->with('filtroEtapa', $filtroEtapa);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.textos.form')->with('etapas', Etapa::orderBy('ordem', 'asc')->get());
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Texto;

		$object->posts_etapas_id = Input::get('posts_etapas_id');
		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');
		
		if(!Input::get('posts_etapas_id') || !Input::get('titulo')){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(['Erro ao criar Texto! Selecione uma Etapa e um Título']);
		}else{
			try {

				$object->save();

				$object->slug = Str::slug($object->id.'-'.$object->titulo);
				$object->save();

				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Texto criado com sucesso.');
				return Redirect::route('painel.textos.index', array('etapa' => $object->posts_etapas_id));

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(['Erro ao criar Texto!<br>'.$e->getMessage()]);	

			}
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.textos.edit')->with('registro', Texto::find($id))->with('etapas', Etapa::orderBy('ordem', 'asc')->get());
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Texto::find($id);

		$object->posts_etapas_id = Input::get('posts_etapas_id');
		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');
		$object->slug = Str::slug($id.'-'.Input::get('titulo'));
		
		if(!Input::get('posts_etapas_id') || !Input::get('titulo')){
			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(['Erro ao criar Texto! Selecione uma Etapa e um Título']);
		}else{
			try {

				$object->save();
				Session::flash('sucesso', true);
				Session::flash('mensagem', 'Texto alterado com sucesso.');
				return Redirect::route('painel.textos.index', array('etapa' => $object->posts_etapas_id));

			} catch (\Exception $e) {

				Session::flash('formulario', Input::all());
				return Redirect::back()->withErrors(['Erro ao criar Texto!<br>'.$e->getMessage()]);	

			}
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Texto::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Texto removido com sucesso.');

		return Redirect::back();
	}

}

laravel/app/views/backend/textos/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Texto
        </h2>  

		{{ Form::open( array('route' => array('painel.textos.update', $registro->id), 'files' => false, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<div class="form-group">
					<label for="inpuEtapa">Etapa</label>
					<select name="posts_etapas_id" id="inpuEtapa" required class="form-control">
						<option value="">--</option>
						@if($etapas)
							@foreach($etapas as $etapa)
								<option value="{{$etapa->id}}" @if($registro->posts_etapas_id == $etapa->id) selected @endif>{{$etapa->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>

		    	<div class="form-group">
					<label for="inputTitulo">Título</label>
					<input type="text" class="form-control" id="inputTitulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
			</div>

			<div class="form-group">
				<label for="inputTexto">Texto</label>
				<textarea name="texto" class="form-control" id="inputTexto">{{$registro->texto}}</textarea>
			</div>

			<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

			<a href="{{URL::route('painel.textos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/textos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Texto
        </h2>  

		<form action="{{URL::route('painel.textos.store')}}" method="post">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<div class="form-group">
					<label for="inpuEtapa">Etapa</label>
					<select name="posts_etapas_id" id="inpuEtapa" required class="form-control">
						<option value="">--</option>
						@if($etapas)
							@foreach($etapas as $etapa)
								<option value="{{$etapa->id}}" @if(Session::has('formulario') && Session::get('formulario')['posts_etapas_id'] == $etapa->id) selected @endif>{{$etapa->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>

		    	<div class="form-group">
					<label for="inputTitulo">Título</label>
					<input type="text" class="form-control" id="inputTitulo" name="titulo"  @if(Session::has('formulario')) value="{{ Session::get('formulario')['titulo'] }}" @endif required>
				</div>
			</div>

			<div class="form-group">
				<label for="inputTexto">Texto</label>
				<textarea name="texto" class="form-control" id="inputTexto"> @if(Session::has('formulario')) {{ Session::get('formulario')['texto'] }} @endif</textarea>
			</div>

			<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

			<a href="{{URL::route('painel.textos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			
		</form>
    </div>
    
@stop

laravel/app/views/backend/textos/index.blade.php
@section('conteudo')

<div class="container">

	@if(Session::has('sucesso'))
       <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

	@if($errors->any())
		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
	@endif

	<h2>
  		Textos <a href="{{ URL::route('painel.textos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Texto</a>
	</h2>

	@if($etapas)
		<br>
		Selecione uma Etapa:<br>
		<div class="btn-group">
			<?php foreach ($etapas as $key => $value): ?>
				<a href="painel/textos?etapa={{$value->id}}" title="{{$value->titulo}}" class="btn btn-sm @if(isset($filtroEtapa) && $filtroEtapa == $value->id) btn-warning @else btn-default @endif ">{{$value->titulo}}</a>
			<?php endforeach ?>
		</div>
	@endif

	<table class="table table-striped table-bordered table-hover table-sortable" data-tabela="posts">
        
        <thead>
    		<tr>
          		<th>Ordenar</th>
          		<th>Título</th>
          		<th>Texto</th>
      			<th><span class="glyphicon glyphicon-cog"></span></th>
    		</tr>
  		</thead>

  		<tbody>
  		@if($textos && count($textos))
	    	@foreach ($textos as $registro)

	        	<tr class="tr-row" id="row_{{ $registro->id }}">
	              	<td class="move-actions"><a href="#" class="btn btn-info btn-move btn-sm">mover</a></td>
	              	<td>{{$registro->titulo}}</td>
	              	<td>{{Str::words(strip_tags($registro->texto), 15)}}</td>
	          		<td class="crud-actions">
	            		<a href="{{ URL::route('painel.textos.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

	            	   	{{ Form::open(array('route' => array('painel.textos.destroy', $registro->id), 'method' => 'delete')) }}
	                    	<button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
	                   	{{ Form::close() }}
	          		</td>
	        	</tr>

	    	@endforeach
    	@else
			<tr>
				<td colspan="4">
					<h3>
						@if($filtroEtapa)
							Nenhum Texto Encontrado para a Etapa
						@else
							Selecione uma Etapa
						@endif
					</h3>
				</td>
			</tr>
    	@endif
  		</tbody>

    </table>
    
</div>

@stop